// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/auth/session": {
    params: {};
  };
  "/api/user/profile": {
    params: {};
  };
  "/posts": {
    params: {};
  };
  "/replies": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/auth/session" | "/api/user/profile" | "/posts" | "/replies";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/login";
  };
  "routes/auth/session.tsx": {
    id: "routes/auth/session";
    page: "/auth/session";
  };
  "routes/api/user-profile.server.ts": {
    id: "routes/api/user-profile.server";
    page: "/api/user/profile";
  };
  "routes/dashboard/index.tsx": {
    id: "routes/dashboard/index";
    page: "/" | "/posts" | "/replies";
  };
  "routes/dashboard/overview.tsx": {
    id: "routes/dashboard/overview";
    page: "/";
  };
  "routes/dashboard/posts.tsx": {
    id: "routes/dashboard/posts";
    page: "/posts";
  };
  "routes/dashboard/replies.tsx": {
    id: "routes/dashboard/replies";
    page: "/replies";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/auth/login": typeof import("./app/routes/auth/login.tsx");
  "routes/auth/session": typeof import("./app/routes/auth/session.tsx");
  "routes/api/user-profile.server": typeof import("./app/routes/api/user-profile.server.ts");
  "routes/dashboard/index": typeof import("./app/routes/dashboard/index.tsx");
  "routes/dashboard/overview": typeof import("./app/routes/dashboard/overview.tsx");
  "routes/dashboard/posts": typeof import("./app/routes/dashboard/posts.tsx");
  "routes/dashboard/replies": typeof import("./app/routes/dashboard/replies.tsx");
};