// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/posts": {
    params: {};
  };
  "/posts/new": {
    params: {};
  };
  "/posts/:id": {
    params: {
      "id": string;
    };
  };
  "/replies": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/logout" | "/posts" | "/posts/new" | "/posts/:id" | "/replies";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/login";
  };
  "routes/auth/logout.tsx": {
    id: "routes/auth/logout";
    page: "/logout";
  };
  "routes/dashboard/index.tsx": {
    id: "routes/dashboard/index";
    page: "/" | "/posts" | "/posts/new" | "/posts/:id" | "/replies";
  };
  "routes/dashboard/overview.tsx": {
    id: "routes/dashboard/overview";
    page: "/";
  };
  "routes/dashboard/posts/index.tsx": {
    id: "routes/dashboard/posts/index";
    page: "/posts";
  };
  "routes/dashboard/posts/new.tsx": {
    id: "routes/dashboard/posts/new";
    page: "/posts/new";
  };
  "routes/dashboard/posts/[post].tsx": {
    id: "routes/dashboard/posts/[post]";
    page: "/posts/:id";
  };
  "routes/dashboard/replies.tsx": {
    id: "routes/dashboard/replies";
    page: "/replies";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/auth/login": typeof import("./app/routes/auth/login.tsx");
  "routes/auth/logout": typeof import("./app/routes/auth/logout.tsx");
  "routes/dashboard/index": typeof import("./app/routes/dashboard/index.tsx");
  "routes/dashboard/overview": typeof import("./app/routes/dashboard/overview.tsx");
  "routes/dashboard/posts/index": typeof import("./app/routes/dashboard/posts/index.tsx");
  "routes/dashboard/posts/new": typeof import("./app/routes/dashboard/posts/new.tsx");
  "routes/dashboard/posts/[post]": typeof import("./app/routes/dashboard/posts/[post].tsx");
  "routes/dashboard/replies": typeof import("./app/routes/dashboard/replies.tsx");
};